version: '3'
services:
  influxdb:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`subdomain.hostname.de`)"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '127.0.0.1:8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=dm
      - DOCKER_INFLUXDB_INIT_BUCKET=arduino
    volumes:
      - ./data/influxdb-data:/var/lib/influxdb2
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true